config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'maisons', to: 'pages#maisons'
  get 'about_us', to: 'pages#about_us'
  get 'service', to: 'pages#service'
  get 'contact', to: 'pages#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base

  validates :email,
    :presence => :true,
    :format => {
      :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i,
      :message => "must be a valid email address"
    }
  validates :message, :presence => :true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/contact_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])

    if @contact.save
      ContactsMailer.general_message(@contact).deliver
      render :thanks
    else
      render :new
    end
  end

  def thanks
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def maisons
  end

  def about_us
  end

  def service
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Résidences Belex</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <style>
      body {
        background: rgba(195, 229, 152, 0.55);
        /*background-image: url('/assets/DSC_0358 copie.JPG');*/
      }
    </style>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/about_us.html.erb
<div class="container">

  <div class="idea-titre">
    <h2>Naissance d’une idée …</h2>
  </div>

  <div class="idea-box">
    <p>Le projet est conduit par BELTRAN Valérie, cadre de santé en EHPAD  et fortement soutenue par Jerôme EXPERT, cadre  informaticien hospitalier d'où le nom BEL-EX comme l'abréviation des deux noms de famille mais aussi comme le début d'une BEL-lle EX-périence ?
    <br><br>
    Ce projet est réfléchi depuis plus de 4 ans, a évolué grâce aux  échanges avec les familles, avec les séniors et surtout après réflexion et analyse de mes expériences professionnelles.
    <br><br>
    Il a donc été motivé par l’envie, voire le besoin, de proposer un nouveau modèle de vie pour nos séniors quand l’entrée en institution n’est pas souhaitée mais les années passant, la solitude  ou la dépendance s’installe, la situation devient alors difficile.
    <br><br>
    Ce nouveau modèle de colocation leur permettra de reculer ou d’éviter l’entrée en EHPAD. 
    La maison partagée en colocation est entre le foyer logement et la maison de retraite.  <br>
    Les séniors pourront organiser leur quotidien dans un environnement sécurisé et sécurisant pour eux-mêmes et leur famille.
    <br><br>
    L'objectif est que chacun puisse vivre comme à la maison tout en partageant des moments de communauté et de convivialité à plusieurs .
    <br><br>
    La maison partagée sera un lieu respectueux des habitudes individuelles. <br>
    Elle se définit comme un habitat partagé, une colocation pour seniors valides et elle apporte une aide quotidienne grâce à la gouvernante.</p>
  </div>

  <div class="avantages-titre">
    <h2>Les avantages de l’habitat partagé</h2>
  </div>

  <div class="avantages-box">
    <p>Hormis l’avantage de ne plus vivre seul et en toute sécurité, la vie dans une maison partagée permet de réduire les coûts :
    <br><br>
    Frais partagés des charges et du loyer de la maison <br>
    Frais partagés du service à la personne <br>
    Avantages fiscaux : crédit et réductions d’impôts sur le service à la personne
    <br><br>
    APL, APA <br>
    Mais aussi, <br>
    Vous gardez vos professionnels de santé <br>
    La maison accueille vos petits meubles et vos petits animaux de compagnie. <br>
    Vous pouvez la décorer à votre goût. <br>
    Chambre double pour les couples <br>
    </p>
  </div>


</div>

app/views/pages/contact.html.erb
<div class="container">

  <div class="row" style="margin-top: 100px;">

    <div class="col-sm-6" style="margin-left: auto; margin-right: auto;">

      <!-- BOX1 LEFT -->
      <div class="contact-box row">
        <div class="col">
          <div class="partie1 row">
            <p>Contactez-nous!</p>
          </div>
          <div class="partie2 row">
            <a  href="mailto:residences.belex@gmail.com">
              <p>residences.belex@gmail.com</p>
            </a>
          </div>
          <div class="partie3 row">
            <p>07.67.38.17.16</p>
          </div>
          <div class="partie4 row">
            <a target="_blank" href="https://fr-fr.facebook.com/ResidenceBelex/">
            <%= image_tag("logo-fb.png") %>
          </a>
          </div>
        </div>
      </div>

      <!-- BOX2 LEFT -->
      <div class="logo-contact row">
        <%= image_tag "logoBelex.png"%>
      </div>

    </div>

    <!-- BOX RIGHT -->
<!--     <div class="formulaire-box col-sm-6">
      <div class="titre-form row">
        <p>Pour plus de renseignements, <br>
          remplissez ce formulaire:
        </p>
      </div>
      <div class="line">
      </div>
      <div class="formulaire">
        <p style="display: flex; justify-content: center; margin: 100px;">À venir...</p>
      </div>

    </div> -->

  </div>
</div>

app/views/pages/home.html.erb
<div class="container">

  <div class="titre">
    <h1>Résidences Belex</h1>
  </div>

  <div class="sous-titre">
    <h2>Colocation entre seniors</h2>
  </div>

  <div class="intro-box">
    <p>Vous souhaitez continuer à vivre dans un environnement familier mais vivre seul ou à la charge de vos enfants, commence à être difficile. <br>
    Savoir que nous veillerons sur vous tout en respectant vos habitudes de vie et en vous garantissant une liberté d’organiser votre vie en fonction de vos envies et de vos possibilités peut être la solution .
    <br><br>
    Peut-être seriez-vous, alors, intéressés par l’idée de la maison d’habitation partagée, dans laquelle vous aurez votre intimité tout en rencontrant d’autres personnes dans les lieux communs, lorsque vous le choisirez, pour des échanges, des activités communes et une vie citoyenne ?  
    <br><br>
    Nous vous proposons, un modèle souple, basé sur l’entraide et la bienveillance mutuelle.
    <br>
    Vivre ensemble sera notre devise.</p>
  </div>

  <div class="bienvenue">
    <h1>Bienvenue chez vous!</h1>
  </div>

</div>

app/views/pages/maisons.html.erb
<div class="my-slider">

  <input type="radio" id="i1" name="images" checked />
  <input type="radio" id="i2" name="images" />
  <input type="radio" id="i3" name="images" />
  <input type="radio" id="i4" name="images" />
  <input type="radio" id="i5" name="images" />
  <input type="radio" id="i6" name="images" />
  <input type="radio" id="i7" name="images" />
  <input type="radio" id="i8" name="images" />
  <input type="radio" id="i9" name="images" />
  <input type="radio" id="i10" name="images" />
  <input type="radio" id="i11" name="images" />
  <input type="radio" id="i12" name="images" />
  <input type="radio" id="i13" name="images" />
  <input type="radio" id="i14" name="images" />

  <div class="slide_img" id="one">
    <%= cl_image_tag("belex/DSC_0319_aubfbx.jpg", :quality=>"auto") %>

    <label class="prev" for="i14"><span>&#x2039;</span></label>
    <label class="next" for="i2"><span>&#x203a;</span></label>
  </div>

  <div class="slide_img" id="two">
    <%= cl_image_tag("belex/DSC_0380_lqqsze.jpg", :quality=>"auto") %>

    <label class="prev" for="i1"><span>&#x2039;</span></label>
    <label class="next" for="i3"><span>&#x203a;</span></label>
  </div>

  <div class="slide_img" id="three">
    <%= cl_image_tag("DSC_0357_mymemc.jpg", :quality=>"auto") %>

    <label class="prev" for="i2"><span>&#x2039;</span></label>
    <label class="next" for="i4"><span>&#x203a;</span></label>
  </div>

  <div class="slide_img" id="four">
    <%= cl_image_tag("DSC_0394_bz5vcq.jpg", :quality=>"auto") %>

    <label class="prev" for="i3"><span>&#x2039;</span></label>
    <label class="next" for="i5"><span>&#x203a;</span></label>
  </div>

  <div class="slide_img" id="five">
    <%= cl_image_tag("belex/DSC_0377_jyzwcn.jpg", :quality=>"auto") %>

    <label class="prev" for="i4"><span>&#x2039;</span></label>
    <label class="next" for="i6"><span>&#x203a;</span></label>
  </div>

  <div class="slide_img" id="six">
    <%= cl_image_tag("chambre_2_aqntol.jpg", :quality=>"auto") %>

    <label class="prev" for="i5"><span>&#x2039;</span></label>
    <label class="next" for="i7"><span>&#x203a;</span></label>
  </div>

  <div class="slide_img" id="seven">
    <%= cl_image_tag("DSC_0348_cczfvo.jpg", :quality=>"auto") %>

    <label class="prev" for="i6"><span>&#x2039;</span></label>
    <label class="next" for="i8"><span>&#x203a;</span></label>
  </div>

  <div class="slide_img" id="height">
    <%= cl_image_tag("DSC_0349_y8qvx3.jpg", :quality=>"auto") %>

    <label class="prev" for="i7"><span>&#x2039;</span></label>
    <label class="next" for="i9"><span>&#x203a;</span></label>
  </div>

  <div class="slide_img" id="nine">
    <%= cl_image_tag("DSC_0350_hvnv9w.jpg", :quality=>"auto") %>

    <label class="prev" for="i8"><span>&#x2039;</span></label>
    <label class="next" for="i10"><span>&#x203a;</span></label>
  </div>

  <div class="slide_img" id="ten">
    <%= cl_image_tag("chambre_2_sdb_ie8jsg.jpg", :quality=>"auto") %>

    <label class="prev" for="i9"><span>&#x2039;</span></label>
    <label class="next" for="i11"><span>&#x203a;</span></label>
  </div>

  <div class="slide_img" id="eleven">
    <%= cl_image_tag("DSC_0354_vhxxs2.jpg", :quality=>"auto") %>

    <label class="prev" for="i10"><span>&#x2039;</span></label>
    <label class="next" for="i12"><span>&#x203a;</span></label>
  </div>

  <div class="slide_img" id="twelve">
    <%= cl_image_tag("NOTRE_GOUVERNANTE_kjxfkc.jpg", :quality=>"auto") %>

    <label class="prev" for="i11"><span>&#x2039;</span></label>
    <label class="next" for="i13"><span>&#x203a;</span></label>
  </div>

  <div class="slide_img" id="thirteen">
    <%= cl_image_tag("belex/DSC_0400_hkvgew.jpg", :quality=>"auto") %>

    <label class="prev" for="i12"><span>&#x2039;</span></label>
    <label class="next" for="i14"><span>&#x203a;</span></label>
  </div>

  <div class="slide_img" id="fourteen">
    <%= cl_image_tag("belex/DSC_0398_ttocsx.jpg", :quality=>"auto") %>

    <label class="prev" for="i13"><span>&#x2039;</span></label>
    <label class="next" for="i1"><span>&#x203a;</span></label>
  </div>

  <div id="nav_slide">
    <label for="i1" class="dots" id="dot1"></label>
    <label for="i2" class="dots" id="dot2"></label>
    <label for="i3" class="dots" id="dot3"></label>
    <label for="i4" class="dots" id="dot4"></label>
    <label for="i5" class="dots" id="dot5"></label>
    <label for="i6" class="dots" id="dot6"></label>
    <label for="i7" class="dots" id="dot7"></label>
    <label for="i8" class="dots" id="dot8"></label>
    <label for="i9" class="dots" id="dot9"></label>
    <label for="i10" class="dots" id="dot10"></label>
    <label for="i11" class="dots" id="dot11"></label>
    <label for="i12" class="dots" id="dot12"></label>
    <label for="i13" class="dots" id="dot13"></label>
    <label for="i14" class="dots" id="dot14"></label>
  </div>

</div>

<div class="maison-text row">

  <h2>La maison</h2>

  <p>La Résidence Belex est idéalement située à Castelnaudary (Aude), au pied du Grand Bassin (Canal du Midi), à deux pas du centre ville. <br>
  Elle comprend 4 chambres individuelles (deux côté grand bassin, deux côté rue) comprenant toutes une salle d’eau, un WC, placard, TV et équipées d’une sécurité Senioradom.
  <br>
  Pour accéder aux chambres, un système de montes escaliers est installé à tous les étages de la maison en plus des rampes.
  <br>
  Les lieux communs sont la cuisine, la salle à manger et le salon. <br>
  Une agréble terrasse vous accueillera au bord du grand bassin pour des bons moments de détente !</p>

</div>

app/views/pages/service.html.erb
<div class="container">

  <div class="service-titre">
    <h2>Le service à la personne Belex</h2>
  </div>

  <div class="service-box">
    <p>Notre gouvernante est présente tous les jours pour vous accompagner et vous soulager des tâches quotidiennes. Vous serez chouchoutez et ensemble, vous vivrez le quotidien.
    <br>
    Ce service est lié au contrat de location et est dédié exclusivement aux habitants de la résidence. Le nombre d’heures peut donc être augmenté en fonction de la demande.
    <br><br>
    Un soin particulier est prévu à la préparation des repas avec une exigence sur le "manger sain" avec les produits du terroir et une préparation, sur place, qui privilégie la qualité nutritionnelle.
    <br>
    Les repas seront étudiés et préparés en concertations avec les habitants suivant leurs goûts et habitudes, chacun pourra y mettre son grain de sel!
    </p>
  </div>

  <div class="personnel-titre">
    <h2>Le personnel</h2>
  </div>

  <div class="personnel-box" style="margin-bottom: 100px">
    <p>Le fil directeur du personnel est l'adaptation aux besoins individuels des habitants.
      <br>
    Nous vous assurons une présence relationnelle de qualité et discrète. <br>
    Nous partageons tous et toutes de fortes valeurs humaines et nous nous engageons à vous accompagner au quotidien.
      <br><br>
    La nuit (et le jour) la maison est sécurisée par le système SeniorAdom, concepteur d’une domotique et d’une téléassistance à domicile, complété par une personne d’astreinte. Ainsi, en cas de problème ou de besoin, une personne se rendra rapidement sur les lieux. </p>
  </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="row">
    <div class="logo">
      <%= link_to root_path do %>
      <%= image_tag "logoBelex.png", style: "width: 130px;"%>
      <% end %>
    </div>

    <div class="menu-right row">

      <div class="menu-right-home">
        <%= link_to "Accueil", root_path %>
      </div>

      <div class="menu-right-maisons">
        <%= link_to "La maison", maisons_path %>
      </div>

      <div class="menu-right-who">
        <%= link_to "Service à la personne", service_path %>
      </div>

      <div class="menu-right-join">
        <%= link_to "Qui sommes nous?", about_us_path %>
      </div>

      <div class="menu-right-contact">
        <%= link_to "Contact", contact_path %>
      </div>

    </div>
  </div>

    <!-- BURGER DROPDOWN -->
    <div class="burgerleft"  onclick="myFunction(this)">
      <div class="bar1"></div>
      <div class="bar2"></div>
      <div class="bar3"></div>

      <div id="burgerDrop" class="drop-menu-left" >
        <div class="drop-menu-text">
        <%= link_to "Accueil", root_path %>
        </div>
        <div class="drop-menu-text">
        <%= link_to "La maison", maisons_path %>
        </div>
        <div class="drop-menu-text">
        <%= link_to "Service à la personne", service_path %>
        </div>
        <div class="drop-menu-text">
        <%= link_to "Qui sommes nous?", about_us_path %>
        </div>
        <div class="drop-menu-text">
        <%= link_to "Contact", contact_path %>
        </div>
      </div>

      <script>
        function myFunction(x) {
          x.classList.toggle("change");
          document.getElementById("burgerDrop").classList.toggle("show");
        }
        window.onclick = function(event) {
          if (!event.target.matches('.burgerleft')) {
            var dropdowns = document.getElementsByClassName("drop-menu-left");
            var i;
            for (i = 0; i < dropdowns.length; i++) {
              var openDropdown = dropdowns[i];
                if (openDropdown.classList.contains('show')) {
                  openDropdown.classList.remove('show');
                }
              }
            var dropdowns = document.getElementsByClassName("burgerleft");
            var i;
            for (i = 0; i < dropdowns.length; i++) {
              var openDropdown = dropdowns[i];
                if (openDropdown.classList.contains('change')) {
                  openDropdown.classList.remove('change');
                }
              }
            }
          }
        </script>

</div>
</div>